## Basic python and numpy arrays and their operation

In [1]:
import numpy as np

In [5]:
# a basic list in python 
A = [2.0, 8.1, 3.4]

In [6]:
type(A)

list

In [9]:
B = np.array(A) # equivalent to B = np.array([2.0, 8.1, 3.4])
print(B)

[2.  8.1 3.4]


In [12]:
type(B), B.dtype, B.flags

(numpy.ndarray,
 dtype('float64'),
   C_CONTIGUOUS : True
   F_CONTIGUOUS : True
   OWNDATA : True
   WRITEABLE : True
   ALIGNED : True
   WRITEBACKIFCOPY : False
   UPDATEIFCOPY : False)

In [13]:
A.append(6.3)
A

[2.0, 8.1, 3.4, 6.3]

In [15]:
A.pop(1) # -- notice to remove an item from the list, one needs to pass the corresponding location index -- #
A

[2.0, 3.4, 6.3]

In [19]:
B
B.sort() # -- equivalently np.sort(B) -- #

In [20]:
B

array([2. , 3.4, 8.1])

In [21]:
np.ndarray.sort??

### array indexing 

In [22]:
x = np.array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'])

In [23]:
x.shape

(10,)

#### <font color=blue>The basic slice syntax is $i:j:k$ where $i$ is the starting index, $j$ is the stopping index, and $k$ is the step $(k\neq0)$. This selects the m elements (in the corresponding dimension) with index values $i, i + k, …, i + (m - 1) k$ where $m = q + (r\neq0)$ and $q$ and $r$ are the quotient and remainder obtained by dividing $j - i$ by $k: j - i = q k + r$, so that $i + (m - 1) k < j$.</font>



In [26]:
x[1:7:2] # -- "1:7" picks up 'B' --> 'F'. Then ":2" picks up every 2nd element of the reduced array

array(['B', 'D', 'F'], dtype='<U1')

In [33]:
x[3:], x[:3] # -- c[p:] --> all the elements starting from index p, x[:q] ---> all the elements upto index q

(array(['D', 'E', 'F', 'G', 'H', 'I', 'J'], dtype='<U1'),
 array(['A', 'B', 'C'], dtype='<U1'))

In [34]:
x[:3].tolist() + x[3:].tolist() # -- notice that we converted the numpy array to list.
# --- why can't we work with the numpy.ndarray structure ? 

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

#### <font color=blue>Negative $i$ and $j$ are interpreted as $n + i$ and $n + j$ where $n$ is the number of elements in the corresponding dimension. Negative $k$ makes stepping go towards smaller indices.</font>

In [37]:
x[-2:10], x[-3:3:-1]

(array(['I', 'J'], dtype='<U1'), array(['H', 'G', 'F', 'E'], dtype='<U1'))

In [43]:
x[[2,3,4]] # -- by passing the positions as a list, a subset of an array can be extracted

array(['C', 'D', 'E'], dtype='<U1')

In [72]:
np.arange(1, 100, 2) # --- can be used for any range for fractional interval

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [76]:
np.linspace(0., 2., 8) # ---- make equal interval of numbers 

array([0.        , 0.28571429, 0.57142857, 0.85714286, 1.14285714,
       1.42857143, 1.71428571, 2.        ])

## Higher dimensional arrays

In [78]:
x = np.random.rand( 3,3,4 ) # -- create a rank-3 object of shape (3,3,4)

In [79]:
x

array([[[0.38527263, 0.27432581, 0.99989372, 0.40856625],
        [0.61046266, 0.26557433, 0.66006489, 0.81990809],
        [0.0461216 , 0.15419006, 0.02791278, 0.7043621 ]],

       [[0.04734626, 0.92618022, 0.49187228, 0.51781225],
        [0.31915643, 0.51424004, 0.4665466 , 0.92213355],
        [0.08683827, 0.82736058, 0.8465105 , 0.52261718]],

       [[0.06202154, 0.42877086, 0.46427123, 0.4994193 ],
        [0.49687162, 0.96958366, 0.47671917, 0.65181496],
        [0.74291665, 0.75697078, 0.40612928, 0.96353453]]])

In [83]:
np.where(x > 0.5)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]),
 array([0, 1, 1, 1, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2]),
 array([2, 0, 2, 3, 3, 1, 3, 1, 3, 1, 2, 3, 1, 3, 0, 1, 3]))

In [80]:
x[ np.where(x > 0.5) ]

array([0.99989372, 0.61046266, 0.66006489, 0.81990809, 0.7043621 ,
       0.92618022, 0.51781225, 0.51424004, 0.92213355, 0.82736058,
       0.8465105 , 0.52261718, 0.96958366, 0.65181496, 0.74291665,
       0.75697078, 0.96353453])

In [117]:
X = np.array( [
    ['A11', 'A12', 'A13'],
    ['A21', 'A22', 'A23'],
    ['A31', 'A32', 'A33']
] )

In [118]:
X

array([['A11', 'A12', 'A13'],
       ['A21', 'A22', 'A23'],
       ['A31', 'A32', 'A33']], dtype='<U3')

In [119]:
np.transpose(X), np.transpose(X, (1,0)), X.T # --- possible to pass the index of dimension to permute

(array([['A11', 'A21', 'A31'],
        ['A12', 'A22', 'A32'],
        ['A13', 'A23', 'A33']], dtype='<U3'),
 array([['A11', 'A21', 'A31'],
        ['A12', 'A22', 'A32'],
        ['A13', 'A23', 'A33']], dtype='<U3'),
 array([['A11', 'A21', 'A31'],
        ['A12', 'A22', 'A32'],
        ['A13', 'A23', 'A33']], dtype='<U3'))

In [91]:
# From a 4x3 array the corner elements should be selected using advanced indexing. 
# Thus all elements for which the column is one of [0, 2] and the row is one of [0, 3] need to be selected. 
# To use advanced indexing one needs to select all elements explicitly. 
# Using the method explained previously one could write:

x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])

In [92]:
rows = np.array([[0, 0],
                 [3, 3]], dtype=np.intp)

columns = np.array([[0, 2],
                    [0, 2]], dtype=np.intp)

x[rows, columns]

array([[ 0,  2],
       [ 9, 11]])

### Reshaping tensors and mathematical operation

In [100]:
np.arange(24).reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [102]:
np.arange(24).reshape(4,2,3) # -- 4 pieces of 2X3 matrices

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [120]:
X = np.array([[ 0,  1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10, 11],
              [12, 13, 14, 15, 16, 17],
              [18, 19, 20, 21, 22, 23]
             ]
            )

In [121]:
X[:,2] # -- pick out the 3rd column

array([ 2,  8, 14, 20])

In [122]:
X[1,:] # -- pick out the 2nd row

array([ 6,  7,  8,  9, 10, 11])

In [113]:
np.sum??

In [123]:
np.sum(X, axis=0), np.sum(X, axis=1) # -- algebraic operations can be carried out along particular dimension

(array([36, 40, 44, 48, 52, 56]), array([ 15,  51,  87, 123]))

In [124]:
np.mean(X, axis=0)

array([ 9., 10., 11., 12., 13., 14.])

In [126]:
np.diag(X), np.trace(X)

(array([ 0,  7, 14, 21]), 42)

In [132]:
a = 2 * np.ones([2,2])
b = 3 * np.ones([3,3])

In [134]:
a, b

(array([[2., 2.],
        [2., 2.]]),
 array([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]]))

In [135]:
np.outer(a, b)

array([[6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6.]])

### Merging and splitting of matrices

In [151]:
c, d = np.ones([4,4]), 3 * np.ones([4,4])

In [152]:
c, d

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]))

In [153]:
np.concatenate( (c,d), axis=0 ), np.vstack( (c,d)  )

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]))

In [154]:
np.concatenate( (c,d), axis=1 ), np.hstack( (c,d) )

(array([[1., 1., 1., 1., 3., 3., 3., 3.],
        [1., 1., 1., 1., 3., 3., 3., 3.],
        [1., 1., 1., 1., 3., 3., 3., 3.],
        [1., 1., 1., 1., 3., 3., 3., 3.]]),
 array([[1., 1., 1., 1., 3., 3., 3., 3.],
        [1., 1., 1., 1., 3., 3., 3., 3.],
        [1., 1., 1., 1., 3., 3., 3., 3.],
        [1., 1., 1., 1., 3., 3., 3., 3.]]))

In [165]:
C = np.vstack( (c,d)  )


In [167]:
np.vsplit(C, 4)#np.hsplit(C, 2)

[array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[3., 3., 3., 3.],
        [3., 3., 3., 3.]]),
 array([[3., 3., 3., 3.],
        [3., 3., 3., 3.]])]

In [168]:
C.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])